services:
  - type: web
    name: wccis-backend
    runtime: node
    rootDir: backend
    buildCommand: yarn install && yarn build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://wccis.com
      - key: API_RATE_LIMIT
        value: 100
      - key: API_RATE_LIMIT_WINDOW
        value: 15m
      - key: RATE_LIMIT_WINDOW
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
    
  - type: web
    name: wccis-frontend
    runtime: node
    rootDir: frontend
    # Modified build process to fix standalone output issues
    buildCommand: >
      npm ci --no-optional --no-audit --prefer-offline &&
      NODE_OPTIONS='--max-old-space-size=512' ./node_modules/.bin/next build &&
      cp -r public .next/standalone/ &&
      cp -r .next/static .next/standalone/.next/ &&
      npm prune --production
    # Modified start command to correctly serve static files
    startCommand: >
      NODE_ENV=production node .next/standalone/server.js
    # Add plan with memory specifications
    plan: starter
    # Cache configuration for static assets
    disk:
      name: node-cache
      mountPath: /cache
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://wccis.com/api
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT 
        value: "10000"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"