services:
  - type: web
    name: wccis-backend
    runtime: node
    rootDir: backend
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
    
  - type: web
    name: wccis-frontend
    runtime: node
    rootDir: frontend
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: wccis-backend
          type: web
          property: url
        postfix: /api
