services:
  - type: web
    name: wccis-backend
    runtime: node
    rootDir: backend
    buildCommand: yarn install && yarn build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://wccis-frontend.onrender.com
      - key: API_RATE_LIMIT
        value: 100
      - key: API_RATE_LIMIT_WINDOW
        value: 15m
      - key: RATE_LIMIT_WINDOW
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      # You'll need to set these as secret environment variables in Render dashboard
      # - key: SMTP_HOST
      #   sync: false
      # - key: SMTP_PORT
      #   sync: false
      # - key: SMTP_USER
      #   sync: false
      # - key: SMTP_PASS
      #   sync: false
      # - key: AWS_REGION
      #   sync: false
      # - key: AWS_ACCESS_KEY_ID
      #   sync: false
      # - key: AWS_SECRET_ACCESS_KEY
      #   sync: false
      # - key: AWS_S3_BUCKET
      #   sync: false
    
  - type: web
    name: wccis-frontend
    runtime: node
    rootDir: frontend
    # Optimize the build process and clean up unnecessary files
    buildCommand: >
      npm ci --no-optional --no-audit --prefer-offline &&
      npm run build:optimized &&
      npm prune --production &&
      rm -rf .next/cache
    # More fine-tuned Node options for memory efficiency
    startCommand: >
      NODE_OPTIONS="--max-old-space-size=512 
      --no-lazy
      --gc-interval=100
      --max-semi-space-size=16
      --max-executable-size=48" node .next/standalone/server.js
    # Add plan with memory specifications
    plan: starter
    # Clean npm cache during build to reduce memory usage
    buildFilter:
      paths:
        - frontend/src/**
        - frontend/public/**
        - frontend/package.json
        - frontend/next.config.js
    # Health check endpoint to monitor the service
    healthCheckPath: /
    # Cache configuration for static assets
    disk:
      name: node-cache
      mountPath: /cache
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://wccis-backend.onrender.com/api
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: NEXT_SHARP_PATH
        value: /cache/node_modules/sharp
      - key: NEXT_CACHE_DIR
        value: /cache/.next
      - key: npm_config_cache
        value: /cache/npm
