services:
  - type: web
    name: wccis-backend
    runtime: node
    rootDir: backend
    buildCommand: yarn install && yarn build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://wccis-frontend.onrender.com
      - key: API_RATE_LIMIT
        value: 100
      - key: API_RATE_LIMIT_WINDOW
        value: 15m
      - key: RATE_LIMIT_WINDOW
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      # You'll need to set these as secret environment variables in Render dashboard
      # - key: SMTP_HOST
      #   sync: false
      # - key: SMTP_PORT
      #   sync: false
      # - key: SMTP_USER
      #   sync: false
      # - key: SMTP_PASS
      #   sync: false
      # - key: AWS_REGION
      #   sync: false
      # - key: AWS_ACCESS_KEY_ID
      #   sync: false
      # - key: AWS_SECRET_ACCESS_KEY
      #   sync: false
      # - key: AWS_S3_BUCKET
      #   sync: false
    
  - type: web
    name: wccis-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://wccis-backend.onrender.com/api
