services:
  - type: web
    name: wccis-backend
    runtime: node
    rootDir: backend
    buildCommand: yarn install && yarn build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://wccis.com
      - key: API_RATE_LIMIT
        value: 100
      - key: API_RATE_LIMIT_WINDOW
        value: 15m
      - key: RATE_LIMIT_WINDOW
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
    
  - type: web
    name: wccis-frontend
    runtime: node
    nodeVersion: 22.12.0
    rootDir: frontend
    # Enhanced build process to fix webpack bundle5 issue
    buildCommand: >
      npm ci && 
NEXT_PUBLIC_API_URL=https://wccis.com/api NEXT_PUBLIC_SITE_URL=https://wccis.com NODE_ENV=production npm run build && 
node fix-standalone.js && 
      cp -r public .next/standalone/ &&
      cp -r .next/static .next/standalone/.next/ &&
      cp -r .next/server .next/standalone/.next/ &&
      cp server.js .next/standalone/ &&
      cp test-server.js .next/standalone/ &&
      cp standalone-package.json .next/standalone/package.json &&
      cd .next/standalone && npm install --production --no-optional sharp && cd ../.. &&
      npm prune --production
    # Use custom server.js for better error handling and static file serving
    startCommand: >
      NODE_ENV=production 
      NEXT_PUBLIC_API_URL=https://wccis.com/api 
      NEXT_PUBLIC_SITE_URL=https://wccis.com 
      PORT=10000 
      node .next/standalone/server.js
    # Add plan with memory specifications
    plan: starter
    # Cache configuration for static assets
    disk:
      name: node-cache
      mountPath: /cache
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://wccis.com/api
      - key: NEXT_PUBLIC_SITE_URL
        value: https://wccis.com
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT 
        value: "10000"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: NEXT_SHARP_PATH
        value: "./node_modules/sharp"